repository:
  name: dotfiles-nixos
  description: my nixos config
  private: false

  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false

  default_branch: main

  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false

  delete_branch_on_merge: true

branches:
  - name: main
    protection:
      enforce_admins: null
      required_conversation_resolution: true
      required_pull_request_reviews: null
      required_status_checks:
        strict: false
        contexts:
          - "nix-format"
          - "nix-flake-check"
          - "shellcheck"
          - "conventional-commits"
          - "gitleaks"
      required_linear_history: true
      required_signatures: null
      restrictions: null

labels:
  - name: bug
    color: d73a4a
    description: Something isn't working

  - name: enhancement
    color: a2eeef
    description: New feature or request

  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation

  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists

  - name: wontfix
    color: cfd3d7
    description: This will not be worked on