[changelog]
header = """
# Changelog

"""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
    ## {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
          - {% if commit.scope %}{{ commit.scope }}: {% endif %}{{ commit.message | split(pat=": ", n=2) | last | trim }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/xavwe/dotfiles-nixos/commit/{{ commit.id }}))
    {% endfor %}
{% endfor %}

"""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { body = "BREAKING CHANGE", group = "Breaking Changes" },
    { message = ".*!", group = "Breaking Changes" },
    # Skip everything else
    { message = ".*", skip = true },
]

[bump]
features_always_bump_minor = true
breaking_always_bump_major = true