name: format

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  nix-format:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Get octo-sts token
        uses: octo-sts/action@main
        id: octo-sts
        with:
          scope: xavwe/dotfiles-nixos
          identity: format

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          token: ${{ steps.octo-sts.outputs.token }}

      - name: Set up Nix
        uses: cachix/install-nix-action@v25
        with:
          install_url: https://releases.nixos.org/nix/nix-2.18.1/install

      - name: Install alejandra && Format Nix files
        run: nix run nixpkgs#alejandra -- .

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add .
            git commit -m "style(*.nix): format with alejandra"
            git push origin HEAD:${{ github.head_ref || github.ref_name }}
          fi
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}