name: format

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  nix-format:
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.CLAUDE_APP_ID }}
          private_key: ${{ secrets.CLAUDE_PRIVATE_KEY }}

      - name: Configure Git user
        run: |
          git config user.name "octohelper[bot]"
          git config user.email "151943256+octohelper[bot]@users.noreply.github.com"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          token: ${{ steps.generate_token.outputs.token }}

      - name: Set up Nix
        uses: cachix/install-nix-action@v25
        with:
          install_url: https://releases.nixos.org/nix/nix-2.18.1/install

      - name: Install alejandra && Format Nix files
        run: nix run nixpkgs#alejandra -- .

      - name: Commit and push changes
        run: |
          if ! git diff --quiet; then
            git add .
            git commit -m "style(*.nix): format with alejandra"
            git push origin HEAD:${{ github.head_ref || github.ref_name }}
          fi
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
