name: lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@b96fde71c0080358ed6e2d162f11c612c92a97d1
        with:
          app-id: ${{ secrets.CLAUDE_APP_ID }}
          private-key: ${{ secrets.CLAUDE_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Run Shellcheck
        uses: azohra/shell-linter@1e31b7f51d4b172285ff6b0933199f93779c4811
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@b96fde71c0080358ed6e2d162f11c612c92a97d1
        with:
          app-id: ${{ secrets.CLAUDE_APP_ID }}
          private-key: ${{ secrets.CLAUDE_PRIVATE_KEY }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Conventional Commits
        uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@b96fde71c0080358ed6e2d162f11c612c92a97d1
        with:
          app-id: ${{ secrets.CLAUDE_APP_ID }}
          private-key: ${{ secrets.CLAUDE_PRIVATE_KEY }}

      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}

      - uses: gitleaks/gitleaks-action@bf2dc8e55639c1e091e9b45970152e4313705814
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}