name: lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.CLAUDE_APP_ID }}
          private_key: ${{ secrets.CLAUDE_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.CLAUDE_APP_ID }}
          private_key: ${{ secrets.CLAUDE_PRIVATE_KEY }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          
      - name: Conventional Commits
        uses: wagoid/commitlint-github-action@v6
