name: lint

on:
  push:
  pull_request:
  workflow_run:
    workflows: ["format", "lint", "security", "test"]
    types:
      - completed

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Conventional Commits
        uses: wagoid/commitlint-github-action@v6