name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(main): release')"
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.CLAUDE_APP_ID }}
          private_key: ${{ secrets.CLAUDE_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          token: ${{ steps.generate_token.outputs.token }}
