name: release
on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@8ab05a8a84060745bdc8f0b4f6d8f403c29e06b8
        with:
          app-id: ${{ secrets.CLAUDE_APP_ID }}
          private-key: ${{ secrets.CLAUDE_PRIVATE_KEY }}

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v24

      - name: Install git-cliff
        run: |
          nix profile install nixpkgs#git-cliff

      - name: Check for new version
        id: version
        run: |
          # Get the current version from the latest tag
          CURRENT_VERSION=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//' || echo "0.0.0")
          echo "Current version: $CURRENT_VERSION"

          # Count feat and fix commits since last tag (or all commits if no tags)
          if [ "$CURRENT_VERSION" = "0.0.0" ]; then
            # No tags exist, check all commits
            FEAT_COUNT=$(git log --oneline --grep="^feat" | wc -l)
            FIX_COUNT=$(git log --oneline --grep="^fix" | wc -l)
            BREAKING_COUNT=$(git log --oneline --grep="BREAKING CHANGE\|!" | wc -l)
          else
            # Check commits since last tag
            LAST_TAG="v$CURRENT_VERSION"
            FEAT_COUNT=$(git log $LAST_TAG..HEAD --oneline --grep="^feat" | wc -l)
            FIX_COUNT=$(git log $LAST_TAG..HEAD --oneline --grep="^fix" | wc -l)
            BREAKING_COUNT=$(git log $LAST_TAG..HEAD --oneline --grep="BREAKING CHANGE\|!" | wc -l)
          fi

          echo "Found $FEAT_COUNT features, $FIX_COUNT fixes, $BREAKING_COUNT breaking changes"

          # Determine version bump
          if [ "$BREAKING_COUNT" -gt 0 ]; then
            if [ "$CURRENT_VERSION" = "0.0.0" ]; then
              NEW_VERSION="1.0.0"
            else
              IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
              NEW_VERSION="$((VERSION_PARTS[0] + 1)).0.0"
            fi
          elif [ "$FEAT_COUNT" -gt 0 ]; then
            if [ "$CURRENT_VERSION" = "0.0.0" ]; then
              NEW_VERSION="0.1.0"
            else
              IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
              NEW_VERSION="${VERSION_PARTS[0]}.$((VERSION_PARTS[1] + 1)).0"
            fi
          elif [ "$FIX_COUNT" -gt 0 ]; then
            if [ "$CURRENT_VERSION" = "0.0.0" ]; then
              NEW_VERSION="0.0.1"
            else
              IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
              NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$((VERSION_PARTS[2] + 1))"
            fi
          else
            echo "No feat or fix commits found"
            echo "should_release=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "should_release=true" >> $GITHUB_OUTPUT
          echo "new_version=v$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version will be: v$NEW_VERSION"



      - name: Generate changelog
        id: generate-changelog
        if: steps.version.outputs.should_release == 'true'
        run: |
          CHANGELOG_FILE="RELEASE_NOTES.md"
          # Only include feat and fix commits in changelog
          git-cliff --latest --strip header --include-path "feat*,fix*" > "$CHANGELOG_FILE"
          echo "changelog=$CHANGELOG_FILE" >> $GITHUB_OUTPUT

      - name: Create release
        if: steps.version.outputs.should_release == 'true'
        run: |
          gh release create ${{ steps.version.outputs.new_version }} \
            --title "Release ${{ steps.version.outputs.new_version }}" \
            --notes-file ${{ steps.generate-changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}