name: release

on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(main): release')"
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b
        with:
          app-id: ${{ secrets.CLAUDE_APP_ID }}
          private-key: ${{ secrets.CLAUDE_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - id: release-please
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445
        with:
          token: ${{ steps.generate-token.outputs.token }}
          config-file: .release.json
          skip-labeling: true

      - name: Enable auto-merge
        if: ${{ steps.release-please.outputs.pr }}
        run: gh pr merge ${{ fromJson(steps.release-please.outputs.pr).number }} --auto --squash
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}