name: security

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  secretlint:
    name: secretlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v29
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix run .#secretlint