name: security

on:
  push:
  pull_request:
  workflow_run:
    workflows: ["format", "lint", "security", "test"]
    types:
      - completed

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}