name: update
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  flake:
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b
        with:
          app-id: ${{ secrets.CLAUDE_APP_ID }}
          private-key: ${{ secrets.CLAUDE_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          token: ${{ steps.generate-token.outputs.token }}

      - name: Configure Git user
        run: |
          git config user.name "octohelper[bot]"
          git config user.email "151943256+octohelper[bot]@users.noreply.github.com"

      - name: Set up Nix
        uses: cachix/install-nix-action@c134e4c9e34bac6cab09cf239815f9339aaaf84e
        with:
          install_url: https://releases.nixos.org/nix/nix-2.18.1/install

      - name: Update flake.lock
        run: nix flake update

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "chore(flake.lock): update"
          title: "chore(flake.lock): update"
          body: |
            Automated update of flake.lock file.

            This PR will auto-merge if CI passes and there are no conflicts.
          branch: update/flake-lock
          delete-branch: true
          signoff: false

      - name: Enable auto-merge
        if: steps.create-pr.outputs.pull-request-number
        run: gh pr merge ${{ steps.create-pr.outputs.pull-request-number }} --auto --squash
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.CLAUDE_APP_ID }}
          private-key: ${{ secrets.CLAUDE_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Validate Renovate configuration
        run: |
          npx renovate-config-validator .renovate-ci.json

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.6
        with:
          configurationFile: .renovate-ci.json
          token: ${{ steps.generate-token.outputs.token }}
        env:
          LOG_LEVEL: info