name: update
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  flake:
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@b96fde71c0080358ed6e2d162f11c612c92a97d1
        with:
          app-id: ${{ secrets.CLAUDE_APP_ID }}
          private-key: ${{ secrets.CLAUDE_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          token: ${{ steps.generate-token.outputs.token }}

      - name: Configure Git user
        run: |
          git config user.name "octohelper[bot]"
          git config user.email "226188449+octohelper[bot]@users.noreply.github.com"

      - name: Set up Nix
        uses: cachix/install-nix-action@9280e7aca88deada44c930f1e2c78e21c3ae3edd
        with:
          install_url: https://releases.nixos.org/nix/nix-2.18.1/install

      - name: Update flake.lock
        run: nix flake update

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          author: octohelper[bot] <226188449+octohelper[bot]@users.noreply.github.com>
          committer: octohelper[bot] <226188449+octohelper[bot]@users.noreply.github.com>
          commit-message: "chore(flake.lock): update"
          title: "chore(flake.lock): update"
          body: |
            Automated update of flake.lock file.

            This PR will auto-merge if CI passes and there are no conflicts.
          branch: update/flake-lock
          delete-branch: true
          signoff: false

      - name: Enable auto-merge
        if: steps.create-pr.outputs.pull-request-number
        run: gh pr merge ${{ steps.create-pr.outputs.pull-request-number }} --auto --squash
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@b96fde71c0080358ed6e2d162f11c612c92a97d1
        with:
          app-id: ${{ secrets.CLAUDE_APP_ID }}
          private-key: ${{ secrets.CLAUDE_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.8
        with:
          configurationFile: .renovate-ci.json
          token: ${{ steps.generate-token.outputs.token }}
        env:
          LOG_LEVEL: info
